services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: frauddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redpanda:
    image: docker.io/redpandadata/redpanda:latest
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --node-id 0
      - --advertise-kafka-addr redpanda:9092
      - --kafka-addr 0.0.0.0:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/frauddb
      DATABASE_URL_SYNC: postgresql://postgres:password@db:5432/frauddb
      MLFLOW_TRACKING_URI: sqlite:///mlflow.db
      KAFKA_BOOTSTRAP: redpanda:9092
    depends_on:
      db:
        condition: service_healthy
      redpanda:
        condition: service_healthy

volumes:
  pgdata:
